import React, { useState } from 'react';
import { Zap, CheckCircle2, ChevronRight, Calculator, HelpCircle, ArrowRight, ShieldCheck, Sun, DollarSign, RefreshCw, ExternalLink, Leaf } from 'lucide-react';

const NewCustomerPortal = ({ setActiveTab }) => {
  const [activeStep, setActiveStep] = useState(1);
  const [openFaq, setOpenFaq] = useState(null);

  const timelineSteps = [
    { step: 1, title: 'Site Visit', desc: 'Solar engineer evaluates site orientation, shading, and roof structural load.' },
    { step: 2, title: 'Roof Inspection', desc: 'Drone and 3D architectural mapping for optimal solar panel placement.' },
    { step: 3, title: 'Proposal', desc: 'Custom engineering design, yield estimate, payback timeline, and financial quotation.' },
    { step: 4, title: 'Agreement', desc: 'Standard Electricity Board net-metering / net-accounting contract execution.' },
    { step: 5, title: 'Government Approval', desc: 'Fast-track grid interconnection permits from CEB / LECO.' },
    { step: 6, title: 'Installation', desc: 'Certified technician mounting of Tier-1 solar panels and smart inverter.' },
    { step: 7, title: 'Smart Meter Installation', desc: 'Dual-way bi-directional net export energy meter setup.' },
    { step: 8, title: 'Testing & Calibration', desc: 'Grid safety testing, anti-islanding protocol, and inverter sync.' },
    { step: 9, title: 'Power Generation', desc: 'System activation! System starts producing clean power and earning grid revenue.' }
  ];

  const faqs = [
    { q: 'What is the difference between Net Metering, Net Accounting, and Net Plus?', a: 'Net Metering offsets energy usage with energy credits (carried forward up to 10 years). Net Accounting pays monetary credits for excess exported units. Net Plus exports 100% of generated solar electricity for direct monthly monetary payments.' },
    { q: 'How does Net Metering work with CEB and LECO?', a: 'Net Metering allows you to export surplus electricity generated by your solar system back to the national grid. The exported units offset your monthly consumption or generate credits based on official tariff structures.' },
    { q: 'What happens during cloudy or rainy days?', a: 'Modern Tier-1 monocrystalline panels continue to produce electricity under diffuse daylight, generating around 30% - 60% of peak capacity. When solar production is insufficient, your system seamlessly pulls power from the national grid.' },
    { q: 'What is the payback period for a residential solar system?', a: 'Depending on your package (3kW - 10kW) and monthly energy consumption, average ROI payback ranges between 3.2 years to 4.5 years.' }
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16 py-8">
      
      {/* Intro Header */}
      <div className="text-center space-y-4 max-w-3xl mx-auto">
        <span className="px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold uppercase tracking-wider">
          CEB & LECO Approved Solar Schemes
        </span>
        <h1 className="text-3xl sm:text-5xl font-extrabold text-white">
          Explore Sri Lanka Solar <span className="text-amber-400">Interconnection Schemes</span>
        </h1>
        <p className="text-slate-300 text-sm leading-relaxed">
          Learn about Net Metering, Net Accounting, and Net Plus schemes certified by the Ceylon Electricity Board (CEB) and Lanka Electricity Company (LECO).
        </p>

        <div className="pt-4 flex flex-wrap justify-center gap-4">
          <button
            onClick={() => setActiveTab('calculator')}
            className="px-6 py-3 rounded-xl font-bold bg-amber-500 text-slate-950 hover:bg-amber-400 text-xs flex items-center gap-2 shadow-lg shadow-amber-500/20"
          >
            <Calculator className="w-4 h-4" /> Calculate Savings & Payouts
          </button>
          <button
            onClick={() => setActiveTab('packages')}
            className="px-6 py-3 rounded-xl font-bold bg-slate-900 border border-slate-800 text-white hover:border-emerald-500 text-xs"
          >
            View Solar Packages
          </button>
        </div>
      </div>

      {/* 3 CORE SCHEMES CARDS */}
      <div className="space-y-6">
        <div className="text-center max-w-2xl mx-auto">
          <h2 className="text-2xl font-bold text-white">3 Government Solar Schemes</h2>
          <p className="text-xs text-slate-400 mt-1">Select the scheme that matches your investment goals and energy patterns</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          {/* Scheme 1: Net Metering */}
          <div className="glass-card p-6 border border-amber-500/30 rounded-3xl space-y-4 flex flex-col justify-between">
            <div className="space-y-3">
              <div className="w-12 h-12 rounded-2xl bg-amber-500/20 text-amber-400 flex items-center justify-center font-bold text-xl">
                🔋
              </div>
              <span className="text-[10px] text-amber-400 uppercase tracking-widest font-bold">Scheme 1</span>
              <h3 className="text-xl font-extrabold text-white">Net Metering</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Generate your own electricity and feed excess energy into the national grid. Earn <strong>energy credits</strong> that offset electricity drawn at night or on cloudy days.
              </p>
              <div className="p-3 rounded-2xl bg-slate-950 border border-slate-800 space-y-1.5 text-xs">
                <p className="text-slate-400">⚡ <strong>Billing:</strong> Pay only for net usage</p>
                <p className="text-slate-400">🔄 <strong>Credit Carry-Forward:</strong> Up to 10 Years</p>
                <p className="text-emerald-400 font-semibold">Ideal for: Homes seeking bill reduction</p>
              </div>
            </div>
            <button
              onClick={() => setActiveTab('calculator')}
              className="w-full py-2.5 rounded-xl font-bold bg-amber-500/10 border border-amber-500/30 text-amber-400 hover:bg-amber-500 hover:text-slate-950 transition-all text-xs"
            >
              Select Net Metering
            </button>
          </div>

          {/* Scheme 2: Net Accounting */}
          <div className="glass-card p-6 border border-emerald-500/30 rounded-3xl space-y-4 flex flex-col justify-between">
            <div className="space-y-3">
              <div className="w-12 h-12 rounded-2xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold text-xl">
                💰
              </div>
              <span className="text-[10px] text-emerald-400 uppercase tracking-widest font-bold">Scheme 2</span>
              <h3 className="text-xl font-extrabold text-white">Net Accounting</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Receive <strong>monetary credits</strong> for excess exported electricity. You pay for grid usage, while exported units are credited monthly at fixed feed-in tariff rates.
              </p>
              <div className="p-3 rounded-2xl bg-slate-950 border border-slate-800 space-y-1.5 text-xs">
                <p className="text-slate-400">💵 <strong>Compensation:</strong> Fixed Rs./kWh Rate</p>
                <p className="text-slate-400">💳 <strong>Payout:</strong> Credited monthly to account</p>
                <p className="text-emerald-400 font-semibold">Ideal for: Preferred financial returns</p>
              </div>
            </div>
            <button
              onClick={() => setActiveTab('calculator')}
              className="w-full py-2.5 rounded-xl font-bold bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 hover:bg-emerald-500 hover:text-slate-950 transition-all text-xs"
            >
              Select Net Accounting
            </button>
          </div>

          {/* Scheme 3: Net Plus */}
          <div className="glass-card p-6 border border-cyan-500/30 rounded-3xl space-y-4 flex flex-col justify-between">
            <div className="space-y-3">
              <div className="w-12 h-12 rounded-2xl bg-cyan-500/20 text-cyan-400 flex items-center justify-center font-bold text-xl">
                🔄
              </div>
              <span className="text-[10px] text-cyan-400 uppercase tracking-widest font-bold">Scheme 3</span>
              <h3 className="text-xl font-extrabold text-white">Net Plus</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Sell <strong>100% of solar generation</strong> directly to the national grid without self-consumption. Paid in cash/credit at agreed feed-in tariff rates.
              </p>
              <div className="p-3 rounded-2xl bg-slate-950 border border-slate-800 space-y-1.5 text-xs">
                <p className="text-slate-400">🏢 <strong>Export:</strong> 100% Output to Grid</p>
                <p className="text-slate-400">💸 <strong>Payment:</strong> Monetary cash payouts</p>
                <p className="text-cyan-400 font-semibold">Ideal for: Investors & Commercial Producers</p>
              </div>
            </div>
            <button
              onClick={() => setActiveTab('calculator')}
              className="w-full py-2.5 rounded-xl font-bold bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 hover:bg-cyan-500 hover:text-slate-950 transition-all text-xs"
            >
              Select Net Plus
            </button>
          </div>

        </div>
      </div>

      {/* SCHEME COMPARISON MATRIX TABLE */}
      <div className="glass-card p-8 border border-slate-800 rounded-3xl space-y-4 overflow-x-auto">
        <div className="flex items-center justify-between pb-2 border-b border-slate-800">
          <div>
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              <Zap className="w-5 h-5 text-amber-400" /> Choosing the Right Scheme Matrix
            </h3>
            <p className="text-xs text-slate-400">Comparing technical parameters across the 3 government solar schemes</p>
          </div>
        </div>

        <table className="w-full text-left text-xs border-collapse">
          <thead>
            <tr className="border-b border-slate-800 text-slate-400 uppercase tracking-wider text-[10px]">
              <th className="p-3">Scheme</th>
              <th className="p-3">Self-Use</th>
              <th className="p-3">Export to Grid</th>
              <th className="p-3">Payment Type</th>
              <th className="p-3">Ideal For</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60 text-slate-300">
            <tr className="hover:bg-slate-900/60 transition-all">
              <td className="p-3 font-bold text-amber-400 flex items-center gap-2">
                <span>🔋</span> Net Metering
              </td>
              <td className="p-3 font-semibold text-emerald-400">Yes</td>
              <td className="p-3 font-semibold text-emerald-400">Yes</td>
              <td className="p-3">Energy Credits (10-Yr Carry)</td>
              <td className="p-3">Homes & businesses seeking bill reduction</td>
            </tr>
            <tr className="hover:bg-slate-900/60 transition-all">
              <td className="p-3 font-bold text-emerald-400 flex items-center gap-2">
                <span>💰</span> Net Accounting
              </td>
              <td className="p-3 font-semibold text-emerald-400">Yes</td>
              <td className="p-3 font-semibold text-emerald-400">Yes</td>
              <td className="p-3">Monetary Credit (CEB/LECO Rate)</td>
              <td className="p-3">Those who prefer financial returns</td>
            </tr>
            <tr className="hover:bg-slate-900/60 transition-all">
              <td className="p-3 font-bold text-cyan-400 flex items-center gap-2">
                <span>🔄</span> Net Plus
              </td>
              <td className="p-3 font-semibold text-red-400">No</td>
              <td className="p-3 font-semibold text-emerald-400">Yes (100%)</td>
              <td className="p-3">Monetary Cash Payment</td>
              <td className="p-3">Investors & commercial solar producers</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* WHY GO SOLAR WITH SMART SOLAR */}
      <div className="glass-card p-8 border border-slate-800 rounded-3xl grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
        <div className="space-y-4">
          <span className="text-xs font-bold text-amber-400 uppercase tracking-widest">Why Go Solar?</span>
          <h2 className="text-2xl font-bold text-white">Three Decades of Solar Excellence</h2>
          <p className="text-xs text-slate-300 leading-relaxed">
            With proven technical expertise and official Ceylon Electricity Board (CEB) & Lanka Electricity Company (LECO) grid integration, we power your transition to clean energy.
          </p>
          <ul className="space-y-2.5 text-xs text-slate-300">
            <li className="flex items-center gap-2.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Significantly reduce or eliminate monthly electricity bills</span>
            </li>
            <li className="flex items-center gap-2.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Gain long-term energy independence from grid tariff hikes</span>
            </li>
            <li className="flex items-center gap-2.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Increase residential and commercial property appraisal value</span>
            </li>
            <li className="flex items-center gap-2.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Help build a greener, more sustainable Sri Lanka 🇱🇰</span>
            </li>
          </ul>
        </div>

        {/* Official Resources Links */}
        <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800 space-y-4 text-xs">
          <h4 className="text-sm font-bold text-white flex items-center gap-2">
            <ExternalLink className="w-4 h-4 text-cyan-400" /> Official Utility Resources
          </h4>
          <p className="text-slate-400">
            For detailed and up-to-date information on utility tariff structures and net metering guidelines, visit:
          </p>
          <div className="space-y-3">
            <a
              href="https://www.ceb.lk"
              target="_blank"
              rel="noreferrer"
              className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-slate-200 hover:border-amber-500/50 flex items-center justify-between transition-all"
            >
              <div>
                <span className="font-bold text-amber-400 block">Ceylon Electricity Board (CEB)</span>
                <span className="text-[10px] text-slate-500">www.ceb.lk</span>
              </div>
              <ExternalLink className="w-4 h-4 text-slate-400" />
            </a>

            <a
              href="https://www.leco.lk"
              target="_blank"
              rel="noreferrer"
              className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-slate-200 hover:border-emerald-500/50 flex items-center justify-between transition-all"
            >
              <div>
                <span className="font-bold text-emerald-400 block">Lanka Electricity Company (LECO)</span>
                <span className="text-[10px] text-slate-500">www.leco.lk</span>
              </div>
              <ExternalLink className="w-4 h-4 text-slate-400" />
            </a>
          </div>
        </div>
      </div>

      {/* 9-Step Animated Installation Timeline */}
      <div className="glass-card p-8 border border-slate-800 rounded-3xl space-y-8">
        <div className="text-center space-y-2">
          <h2 className="text-2xl font-bold text-white">9-Step Installation Process</h2>
          <p className="text-xs text-slate-400">Click any step to inspect technical deliverables</p>
        </div>

        <div className="grid grid-cols-3 md:grid-cols-9 gap-2">
          {timelineSteps.map((s) => (
            <button
              key={s.step}
              onClick={() => setActiveStep(s.step)}
              className={`p-3 rounded-2xl border transition-all text-center flex flex-col items-center justify-center ${
                activeStep === s.step
                  ? 'bg-amber-500 text-slate-950 border-amber-400 font-extrabold shadow-lg shadow-amber-500/20'
                  : s.step < activeStep
                  ? 'bg-emerald-500/20 border-emerald-500/40 text-emerald-400'
                  : 'bg-slate-900 border-slate-800 text-slate-400 hover:border-slate-700'
              }`}
            >
              <span className="text-xs font-bold">{s.step}</span>
              <span className="text-[10px] hidden md:block truncate max-w-[70px] mt-0.5">{s.title}</span>
            </button>
          ))}
        </div>

        {timelineSteps.find(s => s.step === activeStep) && (
          <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4 animate-in fade-in">
            <div className="space-y-1 text-left">
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-0.5 rounded-full bg-amber-500/20 text-amber-400 text-xs font-bold">
                  Step {activeStep} of 9
                </span>
                <h4 className="text-lg font-bold text-white">{timelineSteps[activeStep - 1].title}</h4>
              </div>
              <p className="text-xs text-slate-300 leading-relaxed max-w-2xl pt-1">
                {timelineSteps[activeStep - 1].desc}
              </p>
            </div>

            <div className="flex gap-2">
              {activeStep > 1 && (
                <button
                  onClick={() => setActiveStep(activeStep - 1)}
                  className="px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 text-xs text-slate-300 hover:text-white"
                >
                  Previous
                </button>
              )}
              {activeStep < 9 && (
                <button
                  onClick={() => setActiveStep(activeStep + 1)}
                  className="px-4 py-2 rounded-xl bg-amber-500 text-slate-950 text-xs font-bold hover:bg-amber-400 flex items-center gap-1"
                >
                  Next Step <ChevronRight className="w-4 h-4" />
                </button>
              )}
            </div>
          </div>
        )}
      </div>

      {/* FAQ Section */}
      <div className="max-w-4xl mx-auto space-y-6">
        <h2 className="text-2xl font-bold text-white text-center flex items-center justify-center gap-2">
          <HelpCircle className="w-6 h-6 text-amber-400" /> Frequently Asked Questions
        </h2>

        <div className="space-y-3">
          {faqs.map((faq, idx) => (
            <div key={idx} className="glass-card border border-slate-800 rounded-2xl overflow-hidden">
              <button
                onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                className="w-full p-4 text-left font-bold text-sm text-slate-200 flex items-center justify-between hover:text-amber-400"
              >
                <span>{faq.q}</span>
                <span className="text-amber-400 font-extrabold text-lg">{openFaq === idx ? '−' : '+'}</span>
              </button>
              {openFaq === idx && (
                <div className="px-4 pb-4 text-xs text-slate-400 leading-relaxed border-t border-slate-800/60 pt-3">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

    </div>
  );
};

export default NewCustomerPortal;
